name: Deploy to Production

on:
  push:
    branches: [ prod ]

env:
  BASE_URL: "/app"
  MODE: "production"
  API_HOME_URL: ${{ vars.PROD_BACKEND_HOST }}${{ vars.API_HOME_PATH }}
  API_MANAGE_URL: ${{ vars.PROD_BACKEND_HOST }}${{ vars.API_MANAGE_PATH }}
  API_ACCOUNT_URL: ${{ vars.PROD_BACKEND_HOST }}${{ vars.API_ACCOUNT_PATH }}
  API_MEALS_URL: ${{ vars.API_MEALS_URL }}
  API_ROLES_PATH: ${{ vars.PROD_BACKEND_HOST }}${{vars.API_ROLES_PATH}}
  MANAGEMENT_PAGE_URL: ${{ vars.PROD_MANAGEMENT_PAGE_URL }}
  BACKEND_HOST: ${{ vars.PROD_BACKEND_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: |
          export BASE_URL=${{ env.BASE_URL }}
          npm run build
      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist'
          destination-github-username: 'zl-order-system'
          destination-repository-name: 'zl-order-system.github.io'
          user-email: example@example.com
          target-branch: main
          target-directory: app
          create-target-branch-if-needed: true
